### ISSUE TITLE
Deploy Porfolio using GitHub Pages.

### ISSUE THREAD

**Issue by NeckerFree** [NeckerFree/PortfolioV2#12]
Deploy Portfolio page in:
https://neckerfree.github.io/PortfolioV2/

**Comment by thecodechaser** [comment]
## Hi @NeckerFree 👋, 

Your project is complete!  There is nothing else to say other than Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NeckerFree** [comment]
Deploy approved
